name: flutter_ebook_app
description: A Flutter app for eBooks

version: 1.0.2+4

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  provider: ^4.3.2+2
  shared_preferences: ^0.5.12
  flutter_icons: ^1.1.0
  xml2json: ^4.3.0
  fluttertoast: ^7.1.1
  esys_flutter_share: ^1.0.2
  cached_network_image: ^2.3.2+1
  uuid: ^2.2.2
  objectdb: ^1.0.10+1
  epub_viewer: ^0.1.7
  path_provider: ^1.6.18
  dio: ^3.0.10
  permission_handler: ^5.0.1+1
  google_fonts: ^1.1.0
  flutter_spinkit: ^4.1.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - assets/images/
